apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: imgabreuw/deploy-continuo-com-gitops-e-argocd
  newTag: 121af59ee41dcc87b4769afc49322676b374c7b9
